[package]
name = "zombiesplit"
version = "0.1.0"
authors = ["Matt Windsor <mattwindsor91@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3", features = ["cargo", "derive"] }
colored = "2"
css-color-parser = "0.1.2"
env_logger = "0.9.0"
futures = "0.3.19"
itertools = "0.10.3"
log = { version = "0.4", features = ["serde", "std"] }
num-integer = "0.1.44"
rusqlite = { version = "0.26.3", features = ["chrono"] }
r2d2 = "0.8.9"
r2d2_sqlite = "0.19.0"
sdl2 = { version = "0.35.1", features = ["gfx", "image"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_cbor = "0.11.2"
serde_with = "1.11.0"
symbol = "0.1.9" # used for short names
tabwriter = { version = "1", features = [ "ansi_formatting" ] }
tokio = { version = "1", features = [ "full" ] }
tokio-util = { version = "0.6.9", features = [ "codec" ] }
tokio-serde = { version = "0.8.0", features = [ "cbor" ] }
tempfile = "3"
thiserror = "1.0.30"
toml = "0.5.8"

[dev-dependencies]
pretty_assertions = "1.0.0"