[package]
name = "zombiesplit"
version = "0.1.0"
authors = ["Matt Windsor <mattwindsor91@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "3", features = ["cargo", "derive"] }
config = { version = "0.11.0", default-features = false, features = ["toml"] }
colored = "2"
css-color-parser = "0.1.2"
directories = "4.0.1"
env_logger = "0.9.0"
futures = "0.3.19"
http = "0.2.6"
itertools = "0.10.3"
log = { version = "0.4", features = ["serde", "std"] }
num-integer = "0.1.44"
prost = "0.9"
rusqlite = { version = "0.26.3", features = ["chrono"] }
r2d2 = "0.8.9"
r2d2_sqlite = "0.19.0"
sdl2 = { version = "0.35.1", features = ["gfx", "image"] }
semver = "1.0.6"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.11.0"
symbol = "0.1.9" # used for short names
tabwriter = { version = "1", features = [ "ansi_formatting" ] }
tokio = { version = "1", features = [ "full" ] }
tokio-stream = { version = "0.1.8", features = [ "sync" ] }
tempfile = "3"
thiserror = "1.0.30"
toml = "0.5.8"
tonic = { version = "0.6.2", features = [ "transport" ] }

[build-dependencies]
tonic-build = "0.6.2"

[dev-dependencies]
pretty_assertions = "1.0.0"