name = "Sonic CD (2011)"

[segments.pp]
    name = "Palmtree Panic"
    splits = ["pp1", "pp2", "pp3"]
[segments.cc]
    name = "Collision Chaos"
    splits = ["cc1", "cc2", "cc3"]
[segments.tt]
    name = "Tidal Tempest"
    splits = ["tt1", "tt2", "tt3"]
[segments.qq]
    name = "Quartz Quadrant"
    splits = ["qq1", "qq2", "qq3"]
[segments.ww]
    name = "Wacky Workbench"
    splits = ["ww1", "ww2", "ww3"]
[segments.ss]
    name = "Stardust Speedway"
    splits = ["ss1", "ss2", "ss3"]
[segments.mm]
    name = "Metallic Madness"
    splits = ["mm1", "mm2", "mm3"]

[splits.pp1]
    name = "Palmtree Panic 1"
[splits.pp2]
    name = "Palmtree Panic 2"
[splits.pp3]
    name = "Palmtree Panic 3"

[splits.cc1]
    name = "Collision Chaos 1"
[splits.cc2]
    name = "Collision Chaos 2"
[splits.cc3]
    name = "Collision Chaos 3"

[splits.tt1]
    name = "Tidal Tempest 1"
[splits.tt2]
    name = "Tidal Tempest 2"
[splits.tt3]
    name = "Tidal Tempest 3"

[splits.qq1]
    name = "Quartz Quadrant 1"
[splits.qq2]
    name = "Quartz Quadrant 2"
[splits.qq3]
    name = "Quartz Quadrant 3"

[splits.ww1]
    name = "Wacky Workbench 1"
[splits.ww2]
    name = "Wacky Workbench 2"
[splits.ww3]
    name = "Wacky Workbench 3"

[splits.ss1]
    name = "Stardust Speedway 1"
[splits.ss2]
    name = "Stardust Speedway 2"
[splits.ss3]
    name = "Stardust Speedway 3"

[splits.mm1]
    name = "Metallic Madness 1"
[splits.mm2]
    name = "Metallic Madness 2"
[splits.mm3]
    name = "Metallic Madness 3"

[categories.btgs]
name = "Beat the Game (Sonic)"
segments = ["pp", "cc", "tt", "qq", "ww", "ss", "mm"]

[categories.il]
name = "Individual Levels"
