# System configuration for zombiesplit.
#
# You may edit this, but there isn't any way to override parts of the config
# yet, so be careful!

# Window metrics
[ui.window]
	# Window width and height.
	win_w = 320
	win_h = 640
	# Padding of window elements.
	padding = 4
	# Height of various parts of the window.
	# Each is stacked atop each other, with the remaining space being used
	# for the splits.
	header_h = 40
	total_h = 32
	split_h = 16

# Fonts
[ui.fonts.normal]
	# Path to the font bitmap.
	path = "font.png"
	# Number of columns in the font bitmap (rows = 256 / this number).
	metrics.cols = 32
	# Width and height of one character, less padding.
	metrics.char.w = 7
	metrics.char.h = 9
	# Padding between characters (both on screen and in font bitmap).
	metrics.pad.w = 1
	metrics.pad.h = 1
[ui.fonts.large]
	path = "font-l.png"
	metrics.cols = 32
	metrics.char.w = 12
	metrics.char.h = 16
	metrics.pad.w = 1
	metrics.pad.h = 1

[ui.colours]
	# Based on the Endesga EDG32 palette
	bg.window = "rgb(38,43,68)" # Shade
	fg.editor = "rgb(0,149,233)" # Archaeon
	fg.editor_field = "rgb(44,232,245)" # Ion
	fg.cursor = "rgb(246,117,112)" # Peach
	fg.done = "rgb(90,105,136)" # Iron
	fg.normal = "white"
	fg.header = "rgb(192,203,220)" # Zinc
	fg.time_none = "rgb(58,68,102)" # Steel
	fg.time_run_ahead = "rgb(62,137,72)" # Flora
	fg.time_run_behind = "rgb(255,0,68)" # Iiem
	fg.time_split_ahead = "rgb(254,174,52)" # Glow
