[bg]
window = "#2a2f4e"
editor = "#0c0293"
field-editor = "#3003d9"

[fg]
normal = "white"
editor = "#0cf1ff"
field-editor = "#94fdff"
header = "#fdd2ed"

[fg.name]
done = "#657392"
cursor = "#f389f5"
coming = "white"

[fg.pace]
inconclusive = "white"
ahead = "#d3fc7e"
ahead-but-losing = "#5ac54f"
behind-but-gaining = "#f68187"
behind = "#ea323c"
personal-best = "#ffc825"
